---
title: "class05"
author: "Anjali Hamada"
format: pdf
---

```{r}
# install.packages("ggplot2")
# install.packages("gapminder")
# install.packages("dplyr")

library(ggplot2)
#A quick base R plot - not ggplot2
plot(cars)

#Our first ggplot
ggplot(data=cars) + aes(x=speed, y=dist) + geom_point()
```

```{r}
#Our first ggplot
p <- ggplot(data=cars) + aes(x=speed, y=dist) + geom_point()

#Add a line geom with geom_line()
p + geom_line()
#Add a trend line close to the data
p+geom_smooth()
p+geom_smooth(method="lm")
```

```{r}
# Now let's try it with genes!
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
ggplot(genes, aes(x=Condition1, y=Condition2)) + geom_point()

#map State to point color
p <- ggplot(genes) + 
    aes(x=Condition1, y=Condition2, col=State) +
    geom_point()

#change up colors
p + scale_colour_manual( values=c("blue","gray","red") )

#change axis/title labels
p + scale_colour_manual( values=c("blue","gray","red") ) + labs(title="Gene Expression Changes Upon Drug Treatment", x="Control (no drug)", y="Drug Treatment")
```

```{r}
#going further for gapminder
library(gapminder)
library(dplyr)

#filters to only contain rows with year 2007
gapminder_2007 <- gapminder %>% filter(year==2007)

#scatterplot
ggplot(gapminder_2007) + aes(x=gdpPercap, y=lifeExp) + geom_point()

#change alpha (transparency)
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp) +
  geom_point(alpha=0.5)

#map continent to color and population (pop) to size
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) +
  geom_point(alpha=0.5)

#we can also color by pop
ggplot(gapminder_2007) + 
  aes(x = gdpPercap, y = lifeExp, color = pop) +
  geom_point(alpha=0.8)

#adjusting point size
ggplot(gapminder_2007) + 
  aes(x = gdpPercap, y = lifeExp, size = pop) +
  geom_point(alpha=0.5)

#we can make the actual differences be based on point size
ggplot(gapminder_2007) + 
  geom_point(aes(x = gdpPercap, y = lifeExp, size = pop), alpha=0.5) + 
  scale_size_area(max_size = 10)

#doing the same for 1957
gapminder_1957 <- gapminder %>% filter(year==1957)

ggplot(gapminder_1957) + aes(x = gdpPercap, y = lifeExp, color=continent, size = pop) + geom_point(alpha=0.7) + scale_size_area(max_size = 10) 

#including both '57 and '07
gapminder_1957 <- gapminder %>% filter(year==1957 | year==2007)

ggplot(gapminder_1957) + 
  geom_point(aes(x = gdpPercap, y = lifeExp, color=continent, size = pop), alpha=0.7) + scale_size_area(max_size = 10) + facet_wrap(~year)
```

```{r}
# bar charts!
gapminder_top5 <- gapminder %>% 
  filter(year==2007) %>% 
  arrange(desc(pop)) %>% 
  top_n(5, pop)
  gapminder_top5

# a simple bar chart
  ggplot(gapminder_top5) + 
  geom_col(aes(x = country, y = pop))

# top 5 life expectancy in 2007
 ggplot(gapminder_top5) + geom_col(aes(x = country, y = lifeExp))
 
 #fill bars with color
ggplot(gapminder_top5) + geom_col(aes(x = country, y = pop, fill = continent))

#can we fill with a numeric variable like lifeExp?
ggplot(gapminder_top5) + geom_col(aes(x = country, y = pop, fill = lifeExp))

# Plot population size by country. Create a bar chart showing the population (in millions) of the five biggest countries by population in 2007.
ggplot(gapminder_top5) +
  aes(x=reorder(country, -pop), y=pop, fill=country) +
  geom_col(col="gray30") +
  guides(fill="none")

#flipping a bar chart
USArrests$State <- rownames(USArrests)
ggplot(USArrests) +
  aes(x=reorder(State,Murder), y=Murder) +
  geom_col() +
  coord_flip()

#changing format
ggplot(USArrests) +
  aes(x=reorder(State,Murder), y=Murder) +
  geom_point() +
  geom_segment(aes(x=State, 
                   xend=State, 
                   y=0, 
                   yend=Murder), color="blue") +
  coord_flip()
```

```{r}
#animations
library(gapminder)
library(gganimate)

# Setup nice regular ggplot of the gapminder data
ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_color_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  # Facet by continent
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  shadow_wake(wake_length = 0.1, alpha = FALSE)
```

```{r}
# combining plots
library(patchwork)

# Setup some example plots 
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec))
p4 <- ggplot(mtcars) + geom_bar(aes(carb))

# Use patchwork to combine them here:
(p1 | p2 | p3) /
      p4
```

```{r}
sessionInfo()
```
